spring:
  application:
    name: Spotify GraphQL
  config:
    import: optional:classpath:spotify-secrets.yml
  graphql:
    graphiql:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          spotify:
            # You must register your application on the Spotify Developer Dashboard (https://developer.spotify.com/dashboard).
            # After successful registration you obtain the required client id and client secret.
            # If you do not want to commit these values, put the in a git ignored spotify-secrets.yml file (recommended).
            client-id: unknown
            client-secret: unknown
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - playlist-read-private
              - playlist-read-collaborative
              - playlist-modify-public
              - playlist-modify-private
              - user-follow-read
              - user-library-read
              - user-top-read
              - user-read-recently-played
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id

spotify:
  base-url: 'https://api.spotify.com/v1'
